export let details=
[
    {
        id:0,
        detail:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi omnis natus nulla quam, autem ut eum aperiam accusantium et, a ex expedita cupiditate praesentium accusamus, deleniti iusto repudiandae officiis ea?Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae quisquam nobis modi quasi, quidem qui, culpa numquam nesciunt impedit ea at sapiente accusamus quis error ipsa adipisci, molestias reprehenderit atque. Iure, perspiciatis quam, facilis illum accusantium atque, cum eos sunt ratione eum fugiat assumenda. Consectetur consequuntur labore placeat nam facilis asperiores alias sunt dicta earum magni aliquam similique vel eveniet vitae ex pariatur temporibus, dolorem quis natus iste voluptatibus dignissimos. Dicta nam, rerum possimus ducimus facilis magnam tempore illo praesentium veniam aspernatur tenetur culpa, repellendus distinctio est aliquid impedit consequuntur cupiditate aliquam ipsa ipsam. Molestias nostrum a sunt sint saepe?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed autem atque nihil tenetur ipsum expedita voluptatibus veniam recusandae eveniet voluptas quidem totam iste error in, odit porro impedit quam, eius laudantium molestias ratione odio distinctio. Similique magni enim eum nostrum aliquam dolores sunt alias expedita modi asperiores cupiditate qui, non veritatis ea laboriosam! Eos mollitia nisi porro laudantium amet totam asperiores adipisci optio maxime distinctio molestiae, est in nihil alias neque omnis quae officiis voluptas obcaecati debitis nulla. Non voluptas animi necessitatibus quod quidem repellendus sint? Inventore tenetur illo ratione at est, quam, eum commodi sint, sed cumque odit! Nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit reprehenderit et magni mollitia optio impedit fuga maxime in. Officia, quia. Tenetur eius obcaecati ab, ex inventore dolor explicabo suscipit enim!Lorem"
    },
    {
        id:1,
        detail:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi omnis natus nulla quam, autem ut eum aperiam accusantium et, a ex expedita cupiditate praesentium accusamus, deleniti iusto repudiandae officiis ea?Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae quisquam nobis modi quasi, quidem qui, culpa numquam nesciunt impedit ea at sapiente accusamus quis error ipsa adipisci, molestias reprehenderit atque. Iure, perspiciatis quam, facilis illum accusantium atque, cum eos sunt ratione eum fugiat assumenda. Consectetur consequuntur labore placeat nam facilis asperiores alias sunt dicta earum magni aliquam similique vel eveniet vitae ex pariatur temporibus, dolorem quis natus iste voluptatibus dignissimos. Dicta nam, rerum possimus ducimus facilis magnam tempore illo praesentium veniam aspernatur tenetur culpa, repellendus distinctio est aliquid impedit consequuntur cupiditate aliquam ipsa ipsam. Molestias nostrum a sunt sint saepe?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed autem atque nihil tenetur ipsum expedita voluptatibus veniam recusandae eveniet voluptas quidem totam iste error in, odit porro impedit quam, eius laudantium molestias ratione odio distinctio. Similique magni enim eum nostrum aliquam dolores sunt alias expedita modi asperiores cupiditate qui, non veritatis ea laboriosam! Eos mollitia nisi porro laudantium amet totam asperiores adipisci optio maxime distinctio molestiae, est in nihil alias neque omnis quae officiis voluptas obcaecati debitis nulla. Non voluptas animi necessitatibus quod quidem repellendus sint? Inventore tenetur illo ratione at est, quam, eum commodi sint, sed cumque odit! Nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit reprehenderit et magni mollitia optio impedit fuga maxime in. Officia, quia. Tenetur eius obcaecati ab, ex inventore dolor explicabo suscipit enim!Lorem"
    },
    {
        id:2,
        detail:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi omnis natus nulla quam, autem ut eum aperiam accusantium et, a ex expedita cupiditate praesentium accusamus, deleniti iusto repudiandae officiis ea?Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae quisquam nobis modi quasi, quidem qui, culpa numquam nesciunt impedit ea at sapiente accusamus quis error ipsa adipisci, molestias reprehenderit atque. Iure, perspiciatis quam, facilis illum accusantium atque, cum eos sunt ratione eum fugiat assumenda. Consectetur consequuntur labore placeat nam facilis asperiores alias sunt dicta earum magni aliquam similique vel eveniet vitae ex pariatur temporibus, dolorem quis natus iste voluptatibus dignissimos. Dicta nam, rerum possimus ducimus facilis magnam tempore illo praesentium veniam aspernatur tenetur culpa, repellendus distinctio est aliquid impedit consequuntur cupiditate aliquam ipsa ipsam. Molestias nostrum a sunt sint saepe?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed autem atque nihil tenetur ipsum expedita voluptatibus veniam recusandae eveniet voluptas quidem totam iste error in, odit porro impedit quam, eius laudantium molestias ratione odio distinctio. Similique magni enim eum nostrum aliquam dolores sunt alias expedita modi asperiores cupiditate qui, non veritatis ea laboriosam! Eos mollitia nisi porro laudantium amet totam asperiores adipisci optio maxime distinctio molestiae, est in nihil alias neque omnis quae officiis voluptas obcaecati debitis nulla. Non voluptas animi necessitatibus quod quidem repellendus sint? Inventore tenetur illo ratione at est, quam, eum commodi sint, sed cumque odit! Nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit reprehenderit et magni mollitia optio impedit fuga maxime in. Officia, quia. Tenetur eius obcaecati ab, ex inventore dolor explicabo suscipit enim!Lorem"
    },
    {
        id:3,
        detail:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi omnis natus nulla quam, autem ut eum aperiam accusantium et, a ex expedita cupiditate praesentium accusamus, deleniti iusto repudiandae officiis ea?Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae quisquam nobis modi quasi, quidem qui, culpa numquam nesciunt impedit ea at sapiente accusamus quis error ipsa adipisci, molestias reprehenderit atque. Iure, perspiciatis quam, facilis illum accusantium atque, cum eos sunt ratione eum fugiat assumenda. Consectetur consequuntur labore placeat nam facilis asperiores alias sunt dicta earum magni aliquam similique vel eveniet vitae ex pariatur temporibus, dolorem quis natus iste voluptatibus dignissimos. Dicta nam, rerum possimus ducimus facilis magnam tempore illo praesentium veniam aspernatur tenetur culpa, repellendus distinctio est aliquid impedit consequuntur cupiditate aliquam ipsa ipsam. Molestias nostrum a sunt sint saepe?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed autem atque nihil tenetur ipsum expedita voluptatibus veniam recusandae eveniet voluptas quidem totam iste error in, odit porro impedit quam, eius laudantium molestias ratione odio distinctio. Similique magni enim eum nostrum aliquam dolores sunt alias expedita modi asperiores cupiditate qui, non veritatis ea laboriosam! Eos mollitia nisi porro laudantium amet totam asperiores adipisci optio maxime distinctio molestiae, est in nihil alias neque omnis quae officiis voluptas obcaecati debitis nulla. Non voluptas animi necessitatibus quod quidem repellendus sint? Inventore tenetur illo ratione at est, quam, eum commodi sint, sed cumque odit! Nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit reprehenderit et magni mollitia optio impedit fuga maxime in. Officia, quia. Tenetur eius obcaecati ab, ex inventore dolor explicabo suscipit enim!Lorem"
    },
    {
        id:4,
        detail:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi omnis natus nulla quam, autem ut eum aperiam accusantium et, a ex expedita cupiditate praesentium accusamus, deleniti iusto repudiandae officiis ea?Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae quisquam nobis modi quasi, quidem qui, culpa numquam nesciunt impedit ea at sapiente accusamus quis error ipsa adipisci, molestias reprehenderit atque. Iure, perspiciatis quam, facilis illum accusantium atque, cum eos sunt ratione eum fugiat assumenda. Consectetur consequuntur labore placeat nam facilis asperiores alias sunt dicta earum magni aliquam similique vel eveniet vitae ex pariatur temporibus, dolorem quis natus iste voluptatibus dignissimos. Dicta nam, rerum possimus ducimus facilis magnam tempore illo praesentium veniam aspernatur tenetur culpa, repellendus distinctio est aliquid impedit consequuntur cupiditate aliquam ipsa ipsam. Molestias nostrum a sunt sint saepe?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed autem atque nihil tenetur ipsum expedita voluptatibus veniam recusandae eveniet voluptas quidem totam iste error in, odit porro impedit quam, eius laudantium molestias ratione odio distinctio. Similique magni enim eum nostrum aliquam dolores sunt alias expedita modi asperiores cupiditate qui, non veritatis ea laboriosam! Eos mollitia nisi porro laudantium amet totam asperiores adipisci optio maxime distinctio molestiae, est in nihil alias neque omnis quae officiis voluptas obcaecati debitis nulla. Non voluptas animi necessitatibus quod quidem repellendus sint? Inventore tenetur illo ratione at est, quam, eum commodi sint, sed cumque odit! Nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit reprehenderit et magni mollitia optio impedit fuga maxime in. Officia, quia. Tenetur eius obcaecati ab, ex inventore dolor explicabo suscipit enim!Lorem"
    },
    {
        id:5,
        detail:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi omnis natus nulla quam, autem ut eum aperiam accusantium et, a ex expedita cupiditate praesentium accusamus, deleniti iusto repudiandae officiis ea?Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae quisquam nobis modi quasi, quidem qui, culpa numquam nesciunt impedit ea at sapiente accusamus quis error ipsa adipisci, molestias reprehenderit atque. Iure, perspiciatis quam, facilis illum accusantium atque, cum eos sunt ratione eum fugiat assumenda. Consectetur consequuntur labore placeat nam facilis asperiores alias sunt dicta earum magni aliquam similique vel eveniet vitae ex pariatur temporibus, dolorem quis natus iste voluptatibus dignissimos. Dicta nam, rerum possimus ducimus facilis magnam tempore illo praesentium veniam aspernatur tenetur culpa, repellendus distinctio est aliquid impedit consequuntur cupiditate aliquam ipsa ipsam. Molestias nostrum a sunt sint saepe?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed autem atque nihil tenetur ipsum expedita voluptatibus veniam recusandae eveniet voluptas quidem totam iste error in, odit porro impedit quam, eius laudantium molestias ratione odio distinctio. Similique magni enim eum nostrum aliquam dolores sunt alias expedita modi asperiores cupiditate qui, non veritatis ea laboriosam! Eos mollitia nisi porro laudantium amet totam asperiores adipisci optio maxime distinctio molestiae, est in nihil alias neque omnis quae officiis voluptas obcaecati debitis nulla. Non voluptas animi necessitatibus quod quidem repellendus sint? Inventore tenetur illo ratione at est, quam, eum commodi sint, sed cumque odit! Nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit reprehenderit et magni mollitia optio impedit fuga maxime in. Officia, quia. Tenetur eius obcaecati ab, ex inventore dolor explicabo suscipit enim!Lorem"
    }
]